Missing-Person/Models/User.cs
using Microsoft.AspNetCore.Identity;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Missing_Person.Models
{
    public class User: IdentityUser
    {
        [Required(ErrorMessage ="Please enter your first name")]
        public string? FirstName { get; set; }
        [Required(ErrorMessage = "Please enter your last name")]
        public string? LastName { get; set; }

        [Required(ErrorMessage = "Please enter your email")]
        [EmailAddress]
        public string? Email { get; set; }
        public string? PhoneNumber { get; set; }

        [Required(ErrorMessage = "Please enter your address")]
        public string? Address { get; set; }
        public string? City { get; set; }
        public string? Country { get; set; }
        [NotMapped]
        public IFormFileCollection? ProfileImagePath { get; set; }

        [Required(ErrorMessage = "Please enter your password")]
        [DataType(DataType.Password)]
        public string? Password { get; set; }

        [Required(ErrorMessage = "Please confirm your password")]
        [DataType(DataType.Password)]
        [Compare("Password",ErrorMessage="Password and confirmation passworddo not match")]
        public string? ConfirmPassword { get; set; }
        public List<MissingPerson>? MissingPersons { get; set; }
        
    }
}

Missing-Person/Controllers/UserController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Missing_Person.Models;
using Missing_Person.Repository;
using Missing_Person.ViewModel;

namespace Missing_Person.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserRepository iuserRepository;
        private readonly UserManager<User> userManager;
        public UserController(IUserRepository iuserRepository, UserManager<User> userManager)
        {
            this.userManager = userManager;
            this.iuserRepository = iuserRepository;
        }

        [HttpGet]
        public IActionResult MyProfile(User user)
        {
            var userID = userManager.GetUserId(HttpContext.User);
            User model = iuserRepository.GetUserById(userID);
            var displayAllUser = new DisplayAllUser
            {
                user = model
            };
            return View(displayAllUser);
        }
        [HttpGet]
        public IActionResult Detail(User user)
        {
            var  model = iuserRepository.GetUserById(user.Id);
            if(model == null)
            {
                return View("NotFound");
            }
            var displayAllUser = new DisplayAllUser
            {
                user = model
            };
            return View(displayAllUser);
        }

        [HttpGet]
        public IActionResult DisplayAll()
        {
            var model = iuserRepository.GetAllUser();
            if (model == null)
            {
                return View("NotFound");
            }
            var displayAllUser = new DisplayAllUser
            {
                users = model
            };
            return View(displayAllUser);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            var user = await userManager.FindByIdAsync(id);

            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {id} cannot be found";
                return View("NotFound");
            }

            EditUserViewModel model = new EditUserViewModel
            {
               users = user,
            };

            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(EditUserViewModel model)
        {
            var user = await userManager.FindByIdAsync(userManager.GetUserId(HttpContext.User));

            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {model.users.Id} cannot be found";
                return View("NotFound");
            }
            else
            {
                user.FirstName = model.users.FirstName;
                user.LastName = model.users.LastName;
                user.UserName = model.users.Email;
                user.Password = model.users.Password;
                user.City = model.users.City;
                user.Country = model.users.Country;
                user.Address = model.users.Address;

                var result = await userManager.UpdateAsync(user);

                if (result.Succeeded)
                {
                    return RedirectToAction("MyProfile");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }

                return View(model);
            }
        }

        public async Task<IActionResult> Delete(string id)
        {
            var user = await userManager.FindByIdAsync(id);

            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {id} cannot be found";
                return View("NotFound");
            }
            else
            {
                var result = await userManager.DeleteAsync(user);

                if (result.Succeeded)
                {
                    return RedirectToAction("DisplayAll");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }

                return View("DisplayAll");
            }       
        }
       
    }
}

Missing-Person/Views/User/Detail.cshtml
@model Missing_Person.ViewModel.DisplayAllUser
@using Microsoft.AspNetCore.Identity
@inject UserManager<User> userManager
@{
    ViewBag.Title = "User Details";
}

<h1 class="display-3">Details</h1>

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <dl class="row">
                <dd class="col-sm-9 disabled visually-hidden">@Model.user.Id</dd>
                <dt class="col-sm-3">First Name:</dt>
                <dd class="col-sm-9">@Model.user.FirstName</dd>

                <dt class="col-sm-3">Last Name:</dt>
                <dd class="col-sm-9">@Model.user.LastName</dd>

                <dt class="col-sm-3">Email:</dt>
                <dd class="col-sm-9">@Model.user.UserName</dd>

                <dt class="col-sm-3">Address:</dt>
                <dd class="col-sm-9">@Model.user.Address</dd>

                <dt class="col-sm-3">City:</dt>
                <dd class="col-sm-9">@Model.user.City</dd>

                <dt class="col-sm-3">Country:</dt>
                <dd class="col-sm-9">@Model.user.Country</dd>
            </dl>
            
        </div>
    </div>
</div>

<style>
    .display-3 {
        font-size: 28px;
        font-weight: normal;
        color: #e63946;
        margin-bottom: 30px;
    }

    .container {
        margin-top: 50px;
    }

    .row {
        margin-bottom: 20px;
    }

    dl.row {
        font-size: 18px;
    }

    dt.col-sm-3 {
        font-weight: normal;
        color: #457b9d;
        margin-bottom: 5px;
    }

    dd.col-sm-9 {
        color: #333;
        margin-bottom: 10px;
    }

    .btn-primary {
        background-color: #457b9d;
        border-color: #457b9d;
        color: #fff;
    }

        .btn-primary:hover,
        .btn-primary:focus {
            background-color: #1d3557;
            border-color: #1d3557;
        }
</style>

Missing-Person/Views/User/DisplayAll.cshtml
@model Missing_Person.ViewModel.DisplayAllUser
@using Microsoft.AspNetCore.Identity
@inject UserManager<User> userManager
@{
    Layout = "_Layout";
}

<h3 class="display-3">All Users</h3>

<div class="container">
    <div class="row">
        @foreach (var user in Model.users)
        {
            <div class="col-md-4">
                <div class="card mb-4">
                    <div class="card-body">
                        <h5 class="card-title">@user.FirstName @user.LastName</h5>
                        <p class="card-text" style="font-size: 17px">@user.UserName</p>
                        <a href="@Url.Action("Detail", "User", new { id = user.Id })" class="btn btn-primary">See Details</a>
                        @if (User.IsInRole("Admin"))
                        {
                            @if (User.Identity.IsAuthenticated)
                            {
                                var userx = await userManager.GetUserAsync(User);
                                if (userx.Id != user.Id)
                                {
                                    <a href="@Url.Action("Delete", "User", new { @user.Id })" class="btn btn-danger">Delete</a>
                                }
                            }
                            
                        }
                    </div>
                </div>
            </div>
        }
    </div>
</div>

<style>
    .container {
        margin-top: 50px;
    }

    .display-3 {
        font-size: 36px;
        font-weight: normal;
        margin-bottom: 30px;
        color: #e63946;
    }

    .row {
        margin-bottom: 20px;
    }

    .card {
        border-color: #eaeaea;
    }

    .card-title {
        font-size: 20px;
        font-weight: bold;
        color: #457b9d;
    }

    .card-text {
        font-size: 17px;
        color: #333;
    }

    .btn-primary {
        background-color: #457b9d;
        border-color: #457b9d;
        color: #fff;
    }

        .btn-primary:hover,
        .btn-primary:focus {
            background-color: #1d3557;
            border-color: #1d3557;
        }

        .btn-primary:active,
        .btn-primary.active {
            background-color: #0b2441;
            border-color: #0b2441;
        }

    .btn-danger {
        background-color: #e63946;
        border-color: #e63946;
        color: #fff;
    }

        .btn-danger:hover,
        .btn-danger:focus {
            background-color: #ba181b;
            border-color: #ba181b;
        }

        .btn-danger:active,
        .btn-danger.active {
            background-color: #8c0e11;
            border-color: #8c0e11;
        }
</style>

Missing-Person/Views/User/Edit.cshtml
@model Missing_Person.ViewModel.EditUserViewModel

@{
    ViewBag.Title = "Edit User Profile";
}

<div class="container">
    <h1 class="display-2">Edit Profile</h1>
    <hr />

    <form asp-action="Edit" asp-controller="User" method="post" class="mt-3">
        <input type="hidden" asp-for="@Model.users.Id" />
        <div asp-validation-summary="All" class="text-danger"></div>

        <div class="form-group">
            <label asp-for="@Model.users.FirstName">First Name</label>
            <input asp-for="@Model.users.FirstName" class="form-control" />
            <span asp-validation-for="@Model.users.FirstName" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="@Model.users.LastName">Last Name</label>
            <input asp-for="@Model.users.LastName" class="form-control" />
            <span asp-validation-for="@Model.users.LastName" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="@Model.users.Email">Email</label>
            <input asp-for="@Model.users.Email" class="form-control" />
            <span asp-validation-for="@Model.users.Email" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="@Model.users.Password">Password</label>
            <input asp-for="@Model.users.Password" class="form-control" />
            <span asp-validation-for="@Model.users.Password" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="@Model.users.Address">Address</label>
            <input asp-for="@Model.users.Address" class="form-control" />
            <span asp-validation-for="@Model.users.Address" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="@Model.users.Country">Country</label>
            <input asp-for="@Model.users.Country" class="form-control" />
            <span asp-validation-for="@Model.users.Country" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="@Model.users.City">City</label>
            <input asp-for="@Model.users.City" class="form-control" />
            <span asp-validation-for="@Model.users.City" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="@Model.users.ConfirmPassword">Enter password to edit</label>
            <input asp-for="@Model.users.ConfirmPassword" class="form-control" />
            <span asp-validation-for="@Model.users.ConfirmPassword" class="text-danger"></span>
        </div>

        <div class="text-center">
            <button type="submit" class="btn btn-primary">Update</button>
            <a asp-controller="User" asp-action="MyProfile" class="btn btn-primary bm-2">Cancel</a>
        </div>
    </form>
</div>

<style>
    .container {
        margin-top: 50px;
    }

    .display-2 {
        font-size: 48px;
        font-weight: bold;
        margin-bottom: 20px;
    }

    hr {
        margin-top: 20px;
        margin-bottom: 20px;
    }

    .form-group {
        margin-bottom: 20px;
    }

    label {
        font-weight: normal;
    }

    .text-danger {
        font-size: 14px;
    }

    .btn-primary {
        background-color: #e63946;
        border-color: #e63946;
        color: #fff;
    }

        .btn-primary:hover,
        .btn-primary:focus {
            background-color: #c61e2e;
            border-color: #c61e2e;
        }

        .btn-primary:active,
        .btn-primary.active {
            background-color: #a51824;
            border-color: #a51824;
        }

    .form-control {
        border-radius: 0;
        border: 1px solid #ccc;
        box-shadow: none;
    }

        .form-control:focus {
            border-color: #e63946;
            box-shadow: none;
        }

    .text-center {
        margin-top: 20px;
    }
</style>

Missing-Person/Views/User/MyProfile.cshtml
@model Missing_Person.ViewModel.DisplayAllUser

@{
    ViewBag.Title = "User Details";
}

<div class="container">
    <h1 class="display-4">Profile Details</h1>

    <div class="row">
        <div class="col-md-6">
            <dl class="row">
                <dt class="col-sm-3">First Name:</dt>
                <dd class="col-sm-9">@Model.user.FirstName</dd>

                <dt class="col-sm-3">Last Name:</dt>
                <dd class="col-sm-9">@Model.user.LastName</dd>

                <dt class="col-sm-3">Email:</dt>
                <dd class="col-sm-9">@Model.user.UserName</dd>

                <dt class="col-sm-3">Password:</dt>
                <dd class="col-sm-9">@Model.user.Password</dd>

                <dt class="col-sm-3">Address:</dt>
                <dd class="col-sm-9">@Model.user.Address</dd>

                <dt class="col-sm-3">City:</dt>
                <dd class="col-sm-9">@Model.user.City</dd>

                <dt class="col-sm-3">Country:</dt>
                <dd class="col-sm-9">@Model.user.Country</dd>
            </dl>

            <a href="@Url.Action("Edit", "User", new { id = Model.user.Id })" class="btn btn-primary">Edit</a>
        </div>
    </div>
</div>

<style>
    .container {
        margin-top: 50px;
    }

    .display-4 {
        font-size: 32px;
        font-weight: bold;
        margin-bottom: 20px;
        color: #e63946;
    }

    .row {
        margin-bottom: 20px;
    }

    dl.row {
        margin-bottom: 30px;
    }

    dt {
        font-weight: normal;
        color: #555;
    }

    dd {
        font-weight: normal;
        color: #333;
    }

    .btn-primary {
        background-color: #457b9d;
        border-color: #457b9d;
        color: #fff;
    }

        .btn-primary:hover,
        .btn-primary:focus {
            background-color: #1d3557;
            border-color: #1d3557;
        }

        .btn-primary:active,
        .btn-primary.active {
            background-color: #0b2441;
            border-color: #0b2441;
        }
</style>